# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: nobetnode.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'nobetnode.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fnobetnode.proto\x12\tnobetnode\"\'\n\x04User\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x13\n\x0b\x62\x61nDuration\x18\x02 \x01(\r\"*\n\x06Result\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2n\n\x0cNobetService\x12-\n\x07\x42\x61nUser\x12\x0f.nobetnode.User\x1a\x11.nobetnode.Result\x12/\n\tUnBanUser\x12\x0f.nobetnode.User\x1a\x11.nobetnode.Resultb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nobetnode_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USER']._serialized_start=30
  _globals['_USER']._serialized_end=69
  _globals['_RESULT']._serialized_start=71
  _globals['_RESULT']._serialized_end=113
  _globals['_NOBETSERVICE']._serialized_start=115
  _globals['_NOBETSERVICE']._serialized_end=225
# @@protoc_insertion_point(module_scope)
